
// KULLANICI REDUCER TIPLERİ

export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER = 'SET_USER';
export const LOADING_USER = 'LOADING_USER';
export const MARK_NOTIFICATIONS_READ = 'MARK_NOTIFICATIONS_READ';

//UI REDUCER TİPLERİ

export const SET_ERRORS = 'SET_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const LOADING_DATA = 'LOADING_DATA';
export const STOP_LOADING_UI = 'STOP_LOADING_UI';

// DATA REDUCER TİPLERİ
export const SET_WHOOPS = 'SET_WHOOPS';
export const SET_WHOOP = 'SET_WHOOP';
export const LIKE_WHOOP = 'LIKE_WHOOP';
export const UNLIKE_WHOOP = 'UNLIKE_WHOOP';
export const DELETE_WHOOP = 'DELETE_WHOOP';
export const POST_WHOOP = 'POST_WHOOP';
export const SUBMIT_COMMENT = 'SUBMIT_COMMENT';

